### ISSUE TITLE
Error when disconnected activity inside a FlowChart node

### ISSUE THREAD

**Issue by b0rv3g4r4** [elsa-workflows/elsa-studio#77] opened 2023-11-07 18:14 UTC
I found that when we have a workflow that act as Activity and is disconnected from all activities, we cannot see the instance in the Instance view.

It throw an "The node must be of type 'JsonObject'."

![Captura de pantalla 2023-11-07 a las 19 10 12](https://github.com/elsa-workflows/elsa-studio/assets/34290325/e7e49c28-e0d8-4c5b-8044-82be2ccbcd15)

For more info:
![Captura de pantalla 2023-11-07 a las 19 10 30](https://github.com/elsa-workflows/elsa-studio/assets/34290325/322a88e4-4b00-45f1-b8d0-a80c6ee5b019)
![Captura de pantalla 2023-11-07 a las 19 10 37](https://github.com/elsa-workflows/elsa-studio/assets/34290325/3b8e778f-ab8d-4491-b0e3-011478107cd7)

**Comment by sfmskywalker** [comment] 2023-12-26 19:44
I tried to reproduce the problem as you described, but for me it seems to work just fine. Its possible that this got fixed since you reported it, so I will close it as "cannot reproduce". If you are still able to reproduce this issue with the latest version, then please feel free to reopen it. Thank you.

**Closed as not planned by sfmskywalker** 2023-12-26 19:44 UTC
