### ISSUE TITLE
Incorrect Activity size in instance view

### ISSUE THREAD

**Issue by b0rv3g4r4** [elsa-workflows/elsa-studio#78] opened 2023-11-07 19:57 UTC
Using a big switch (flow), dont adapt the size of the box correctly
![Captura de pantalla 2023-11-07 a las 20 56 02](https://github.com/elsa-workflows/elsa-studio/assets/34290325/83466087-d961-477a-93ec-978de6cc3ce3)

**Comment by sfmskywalker** [comment] 2023-12-26 19:41
It looks like this has been fixed, since I cannot reproduce it. I will close it as such, but if you are still able to reproduce this issue with the latest version, please feel free to reopen. Thanks!

**Closed as not planned** 2023-12-26 19:41 UTC
