### ISSUE TITLE
Looping Issue in V3

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-studio#192] opened 2024-05-13 10:19 UTC
@sfmskywalker ,

After a long time, we are stuck at the point where we are doing one scenario of looping in v3 version. For your information, I am attaching the sample workflow and screenshot as well.

![image](https://github.com/elsa-workflows/elsa-studio/assets/79979623/0f082736-8c52-461f-965b-4580e22353cd)

We have number of events that flows based on call and at the point of decision it loop the call. But when we are triggering the Event4 when condition is false then it is auto-triggerring all the sub-sequent events (Event2 and Event3). It should wait for the Event2 to complete but it is not waiting and going into infinite loop.

Do we have any solution for this? I am attaching sample json as well. Previously in V2, this was working perfectly fine.
[Uploading looping-demo (1).json…]()

**Comment by sfmskywalker** [comment] 2024-05-26 12:47
Hi @sagargolu , I will close this one as a duplicate of #193

**Closed as completed by sfmskywalker** 2024-05-26 12:47 UTC
