### ISSUE TITLE
Copy and pasted activity is not saved 

### ISSUE THREAD

**Issue by ningsun71** [elsa-workflows/elsa-studio#318] opened 2024-11-01 16:37 UTC
I have a workflow with nested ForEach activity. 

![image](https://github.com/user-attachments/assets/c259aa22-5770-47da-b1c8-0286b59da1ba)

If I copy and paste an activity from the root level to the innermost ForEach activity and click the save button. The UI displays the message indicating the workflow is saved. However, when I refresh the page, the copied activity does not appear in the innermost ForEach component. 

This does not happen consistently, but more than 50% of the time. I have confirmed that, the JSON string received by the backend does not contain the copy and pasted activity.

**Comment by sfmskywalker** [comment] 2024-11-12 10:29
I can confirm that something's fishy.

**Comment by sfmskywalker** [comment] 2024-11-12 10:36
What I am seeing is that when I add the third nested ForEach activity and then go back one or two levels, then try to drill into the nested ForEach activities, the 3rd one disappeared.

**Comment by ningsun71** [comment] 2024-12-03 18:29
Hi @sfmskywalker, any updates on this issue?

**Comment by sfmskywalker** [comment] 2024-12-03 18:32
No updates since. It seems to be a tricky issue that might take some time to figure out.

**Comment by locptran** [comment] 2024-12-06 15:49
Hi @sfmskywalker, just wanted to let you know that when I tried elsa workflow using this docker image elsaworkflows/elsa-server-and-studio-v3:latest, it's working as expected. Wondering if something has been changed since

**Comment by sfmskywalker** [comment] 2024-12-06 18:51
Hi @locptran , thanks for chiming in. That's interesting, because no changes were made in this regard. Perhaps you were lucky and it didn't happen when you try. For me, the strange behavior occurs intermittently the first few times, after which it behaved more reliable. It seems that it matters whether you click the design surface prior to pasting in activities, although I am not sure if I observed that correctly.

**Comment by sfmskywalker** [comment] 2024-12-28 09:09
Possibly related: #346

**Comment by sfmskywalker** [comment] 2024-12-28 09:22
I reproduced and resolved the issue. The fix is included in commit #eb016e156b9983027a4a99aad9d354f27019dbee.

**Closed as completed by sfmskywalker** 2024-12-28 09:22 UTC
Labels: bug
