### ISSUE TITLE
[Bug] Using Ctrl+A will crash out the designer view

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-studio#314] opened 2024-10-29 12:11 UTC
1) open a workflow definition
2) use 'select all' command (ctrl+a)
3) see that an error occurs
![image](https://github.com/user-attachments/assets/eacfd3b3-d43d-4d0f-9437-d5c5d731ae0a)
![image](https://github.com/user-attachments/assets/725355a1-872b-463b-9de7-ec6f496de29d)
Symptom: designer view crashes out.
Client version: 3.2.0-rc6.542
Server version: 3.2.1-blueberry.2231

**Comment by TimNguyenVN** [comment] 2024-12-24 04:05
I’m encountering the same issue. When using Ctrl + A in a workflow containing two activities with the Blazor Monaco Editor, the SelectActivity function is triggered for each activity from Js. Upon entering the second activity, this error occurs.

**Comment by TimNguyenVN** [comment] 2024-12-24 04:49
Hi @sfmskywalker, could you kindly take a look at this issue? It doesn't appear in the latest version of the studio Docker image, but I’m unable to determine the exact version it’s built from. I’d greatly appreciate any hints or suggestions you might have to help resolve this. Thank you!

**Comment by TimNguyenVN** [comment] 2024-12-26 09:48
This issue occurs with all tags I’ve tested in GitHub: 3.3.0-rc3, 3.0.0, 3.1.0, and 3.2.0, except for the Docker image only.

**Comment by sfmskywalker** [comment] 2024-12-26 09:57
What about 3.3.0-rc4?

**Comment by sfmskywalker** [comment] 2024-12-26 12:55
I cannot reproduce this issue on the current version (from main). I have tried with Blazor WASM and Blazor Server, also using the latest preview docker images. I will close the issue, but let me know if you can reprosuce it using the latest preview builds.

**Closed as not planned by sfmskywalker** 2024-12-26 12:55 UTC

**Comment by TimNguyenVN** [comment] 2024-12-27 02:09
Hi @sfmskywalker,
I'm able to reproduce this issue from the main branch of Studio. 
Here’s the [recording](https://www.loom.com/share/c14d5b43d73344cb8e360d1e73244ad2?sid=197333de-e5eb-48f6-9dc1-8f12adbe84b8) of my steps.
Note: For elsa-core, I'm using the latest Docker image (`3.3.0-rc3`) as I prefer not to install .NET 9 on my machine.

Additionally, there's an issue that was logged to the console when dragging a script activity into the workflow (as shown at the end of the recording). This can be resolved by commenting out the code `OnDidInit="OnMonacoInitializedAsync"` in the `Code.razor` file. 

Btw, Can you give me the commit Id of Studio in [this image](https://hub.docker.com/layers/elsaworkflows/elsa-server-and-studio-v3/latest/images/sha256-c03c9b1fc58a16a50bdcc3519b6642058baf8520fefe926dcb7ad954b9e4e427)
Thank you!
